<?php

namespace App\Services;

use Illuminate\Support\Facades\Http;
use Illuminate\Support\Str;

class AnthropicSmartCallPlanService
{
    public function suggest(array $payload): array
    {
        $apiKey = config('services.anthropic.api_key');
        $apiUrl = config('services.anthropic.url', 'https://api.anthropic.com/v1/messages');
        $version = config('services.anthropic.version', '2023-06-01');
        $model = config('services.anthropic.model', 'claude-sonnet-4-6');
        $maxTokens = (int) config('services.anthropic.max_tokens', 1024);

        if (!$apiKey) {
            return [
                'priority' => $payload['priority'] ?? 'Medium',
                'reason' => $payload['rule_reason'] ?? 'Generated by business rule.',
                'action' => 'Call customer and confirm their current needs.',
                'script' => 'Hello, we are following up today regarding your recent activity. May I know if you need support?',
            ];
        }

        $promptData = [
            'customer_name' => $payload['customer_name'] ?? null,
            'company_name' => $payload['company_name'] ?? null,
            'customer_type' => $payload['customer_type'] ?? null,
            'orders_count' => $payload['orders_count'] ?? 0,
            'total_spent' => $payload['total_spent'] ?? 0,
            'days_since_last_order' => $payload['days_since_last_order'] ?? null,
            'last_call_result' => $payload['last_call_result'] ?? null,
            'days_since_last_call' => $payload['days_since_last_call'] ?? null,
            'next_call_date' => $payload['next_call_date'] ?? null,
            'plan_type' => $payload['plan_type'] ?? null,
            'priority' => $payload['priority'] ?? null,
            'rule_reason' => $payload['rule_reason'] ?? null,
        ];

        $systemPrompt = <<<TXT
You are a sales planning assistant for Smart Call Plan.

No Customer daa found.
Do not return markdown.
Do not return explanation outside JSON.

Required JSON keys:
priority
reason
action
script

Rules:
- priority must be one of: High, Medium, Low
- reason must be short
- action must be short
- script must be a short phone opening line
TXT;

        $userPrompt = "Customer data:\n" . json_encode($promptData, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);

        $response = Http::withHeaders([
            'x-api-key' => $apiKey,
            'anthropic-version' => $version,
            'content-type' => 'application/json',
        ])->timeout(60)->post($apiUrl, [
            'model' => $model,
            'max_tokens' => $maxTokens,
            'system' => $systemPrompt,
            'messages' => [
                [
                    'role' => 'user',
                    'content' => $userPrompt,
                ],
            ],
        ]);

        if (!$response->successful()) {
            return [
                'priority' => $payload['priority'] ?? 'Medium',
                'reason' => $payload['rule_reason'] ?? 'Generated by business rule.',
                'action' => 'Call customer and confirm their current needs.',
                'script' => 'Hello, we are following up today regarding your recent activity. May I know if you need support?',
            ];
        }

        $text = data_get($response->json(), 'content.0.text', '');

        $cleaned = trim(
            Str::of($text)
                ->replace('```json', '')
                ->replace('```', '')
                ->toString()
        );

        $decoded = json_decode($cleaned, true);

        if (!is_array($decoded)) {
            return [
                'priority' => $payload['priority'] ?? 'Medium',
                'reason' => $payload['rule_reason'] ?? 'Generated by business rule.',
                'action' => 'Call customer and confirm their current needs.',
                'script' => 'Hello, we are following up today regarding your recent activity. May I know if you need support?',
            ];
        }

        return [
            'priority' => $decoded['priority'] ?? ($payload['priority'] ?? 'Medium'),
            'reason' => $decoded['reason'] ?? ($payload['rule_reason'] ?? 'Generated by business rule.'),
            'action' => $decoded['action'] ?? 'Call customer and confirm their current needs.',
            'script' => $decoded['script'] ?? 'Hello, may I quickly follow up with you today?',
        ];
    }
}